### ISSUE TITLE
Latest flatpak fails to run

### ISSUE THREAD

**Issue by pizzadude** [Rosalie241/RMG#48]
When running the latest flatpak, I get this error:
![image](https://user-images.githubusercontent.com/1454420/189502174-448ca8fb-7c95-4970-98e9-8eda7ebe632e.png)

**Comment by pizzadude** [comment]
the portable version works

**Comment by JakobDev** [comment]
This looks like a missing permission. Here is the code for the directory:
https://github.com/Rosalie241/RMG/blob/53044626a0cf60db1938adab83258a4f619d5751/Source/RMG-Core/Directories.cpp#L200-L217

This looks like permission for `xdg-pictures`, but grating this permission does not fix the Issue.

**Comment by Rosalie241** [comment]
I apologize for the issue, removing the `ScreenshotPath` line from the `muoen64plus.cfg` configuration file should resolve this issue.

**Comment by pizzadude** [comment]
Removing the ScreenshotPath line didn't fix it, but changing it to something like:

ScreenshotPath = "/home/username/.var/app/com.github.Rosalie241.RMG/data/RMG/Screenshots"

fixed it. Thanks.

**Comment by DSzero8** [comment]
Hello,

I'm also running into this issue after the most recent update.
Would you happen to know what the directory path is for the mentioned config file?
I'm having trouble finding it on my steamdeck.

Thank you for your time.

**Comment by pizzadude** [comment]
> Hello,
> 
> I'm also running into this issue after the most recent update.
> Would you happen to know what the directory path is for the mentioned config file?
> I'm having trouble finding it on my steamdeck.
> 
> Thank you for your time.

/home/INSERT_YOUR_USERNAME_HERE/.var/app/com.github.Rosalie241.RMG/config/RMG/mupen64plus.cfg

**Comment by DSzero8** [comment]
> > Hello,
> > I'm also running into this issue after the most recent update.
> > Would you happen to know what the directory path is for the mentioned config file?
> > I'm having trouble finding it on my steamdeck.
> > Thank you for your time.
> 
> /home/INSERT_YOUR_USERNAME_HERE/.var/app/com.github.Rosalie241.RMG/config/RMG/mupen64plus.cfg

Got it! Thank you.
I had to show hidden files, and there was no username folder between /home and /.var
Changed screenshots path and I can launch the app now. :)

**Comment by pizzadude** [comment]
> 
I had to show hidden files, and there was no username folder between /home and /.var
Odd, i'm not sure how the steam deck handles things (i'm on fedora kde)

Glad you got it working though.

**Comment by bonzai1888** [comment]
> > > Hello,
> > > I'm also running into this issue after the most recent update.
> > > Would you happen to know what the directory path is for the mentioned config file?
> > > I'm having trouble finding it on my steamdeck.
> > > Thank you for your time.
> > 
> > 
> > /home/INSERT_YOUR_USERNAME_HERE/.var/app/com.github.Rosalie241.RMG/config/RMG/mupen64plus.cfg
> 
> Got it! Thank you. I had to show hidden files, and there was no username folder between /home and /.var Changed screenshots path and I can launch the app now. :)
I tried to fix this, can you offer some guidance on how to do it?

**Comment by DSzero8** [comment]
> > > > Hello,
> > > > I'm also running into this issue after the most recent update.
> > > > Would you happen to know what the directory path is for the mentioned config file?
> > > > I'm having trouble finding it on my steamdeck.
> > > > Thank you for your time.
> > > 
> > > 
> > > /home/INSERT_YOUR_USERNAME_HERE/.var/app/com.github.Rosalie241.RMG/config/RMG/mupen64plus.cfg
> > 
> > 
> > Got it! Thank you. I had to show hidden files, and there was no username folder between /home and /.var Changed screenshots path and I can launch the app now. :)
> > > I tried to fix this, can you offer some guidance on how to do it?

This is how I fixed mine on SteamDeck:
1. I created a "Screenshots" folder in the "Pictures" directory under "Places" when viewed in Dolphin while in desktop mode.
2. Then, go to Home and click on the hamburger icon (Three lines in the top left of the Dolphin file browser)
3. Select the "Show Hidden Files" option
4.  Go into: .var -> app -> com.github.Rasalie241.RMG -> config -> RMG -> open the "mupen64plus.cfg" file
5. Find the "ScreenshotsPath =" section and add the dirctory path for the screenshots path, in my case it looks like this: ScreenshotsPath = "/home/deck/Pictures/Screenshots/"
6. Then save and close the .cfg file
7. Open Rosalie's Mupen GUI and play your games!

Thats how I got mine to work, hope that helps.
Obviously if you create your screenshots folder somewhere else, you'll need to use the correct path.

**Comment by bonzai1888** [comment]
Brilliant, I hadn't created a screenshot folder for a start, so, that was never going to work. Will give this ago later on, cheers.Username...is that just your steam name I take it?Sent from my Galaxy
-------- Original message --------From: DS08 ***@***.***> Date: 12/09/2022  01:11  (GMT+00:00) To: Rosalie241/RMG ***@***.***> Cc: bonzai1888 ***@***.***>, Comment ***@***.***> Subject: Re: [Rosalie241/RMG] Latest flatpak fails to run (Issue #48) 




Hello,
I'm also running into this issue after the most recent update.
Would you happen to know what the directory path is for the mentioned config file?
I'm having trouble finding it on my steamdeck.
Thank you for your time.

/home/INSERT_YOUR_USERNAME_HERE/.var/app/com.github.Rosalie241.RMG/config/RMG/mupen64plus.cfg

Got it! Thank you. I had to show hidden files, and there was no username folder between /home and /.var Changed screenshots path and I can launch the app now. :)

I tried to fix this, can you offer some guidance on how to do it?



This is how I fixed mine on SteamDeck:

I created a "Screenshots" folder in the "Pictures" directory under "Places" when viewed in Dolphin while in desktop mode.
Then, go to Home and click on the hamburger icon (Three lines in the top left of the Dolphin file browser)
Select the "Show Hidden Files" option
Go into: .var -> app -> com.github.Rasalie241.RMG -> config -> RMG -> open the "mupen64plus.cfg" file
Find the "ScreenshotsPath =" section and add the dirctory path for the screenshots path, in my case it looks like this: ScreenshotsPath = "/home/deck/Pictures/Screenshots/"
Then save and close the .cfg file
Open Rosalie's Mupen GUI and play your games!

Thats how I got mine to work, hope that helps.
Obviously if you create your screenshots folder somewhere else, you'll need to use the correct path.

**Comment by Rosalie241** [comment]
Ive made a bugfix release (v0.1.6), should be in the flathub repos in a few hours which should resolve this issue by changing the screenshots directory when it hasnt changed from the broken previous default one from v0.1.4.

**Comment by JakobDev** [comment]
@Rosalie241 You can publish hot fixes directly without waiting.

1. Go to the [Buildserver](https://buildbot.flathub.org)
2. Login with your GitHub Account
3. Wait until the Build is finished
4. Search your Build in "Unpublished builds" list
5. Click on the number to get to the build information
6. Click "Publish"

**Comment by Rosalie241** [comment]
Done, it should be published to the repo now :heart:

**Comment by Rosalie241** [comment]
Considering this issue has been fixed, I'll close this issue 💕
